name: Unreal Engine CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y clang build-essential

    - name: Set up Unreal Engine
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git clone --depth=1 -b 4.26 https://$GH_PAT@github.com/EpicGames/UnrealEngine.git
        cd UnrealEngine
        ./Setup.sh
        ./GenerateProjectFiles.sh
        make

    - name: Build Unreal Project
      run: |
        cd ${{ github.workspace }}
        /path/to/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
          -project=${{ github.workspace }}/IKABombermanUE.uproject \
          -noP4 -platform=Linux -clientconfig=Development -serverconfig=Development \
          -cook -build -stage -pak -archive \
          -archivedirectory=${{ github.workspace }}/output

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Output
        path: ${{ github.workspace }}/output
