name: Unreal Engine CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Unreal Engine Environment
      run: |
        # Replace with steps to download or configure Unreal Engine if necessary
        echo "Assuming Unreal Engine is pre-installed or set up manually"

    - name: Build Unreal Project
      run: |
        & "C:\Path\To\UnrealEngine\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
          -project="$(Build.SourcesDirectory)\IKABombermanUE.uproject" ^
          -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development ^
          -cook -build -stage -pak -archive ^
          -archivedirectory="$(Build.ArtifactStagingDirectory)\output"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Output
        path: $(Build.ArtifactStagingDirectory)/output
